name: publish package to serverless-hub

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install requests
          pip install oss2
      - name: Upload Source Code
        run: |
          ./ossutil64 cp -r ./mq-sdk-quick-start oss://${{ secrets.artifact_bucket }}/mq-sdk-quick-start-source-code-${{  github.ref_name }}/ -i ${{ secrets.access_key_id }} -k ${{ secrets.access_key_secret }} -e ${{ secrets.artifact_endpoint }}
      - name: Publish package
        env:
          AccessKeyId: ${{ secrets.access_key_id }}
          AccessKeySecret: ${{ secrets.access_key_secret }}
          ArtifactEndpoint: ${{ secrets.artifact_endpoint }}
          ArtifactBucket: ${{ secrets.artifact_bucket }}
          RefName: ${{ github.ref_name }}
        run: |
          python publish.py
